sim_metric: "cosine" # choose form ['cosine', 'l2']
keep_hard: True # True for hard examples
Kmeans_with_cos_dist: True # True for using cosine similarity for kmeans clustering
emb_memory_loc: "/data/datasets/hf_cache/out/refinedweb_01_0/fasttext/fasttext_filter/1b-data_influence_model-prediction/emb.npy"
text_emb_memory_loc: None
paths_memory_loc: "/data/datasets/hf_cache/out/refinedweb_01_0/fasttext/fasttext_filter/1b-data_influence_model-prediction/paths.npy"
sorted_clusters_file_loc: "/data/datasets/hf_cache/out/refinedweb_01_0/fasttext/fasttext_filter/1b-data_influence_model-prediction/sorted_clusters"
save_folder: "/data/datasets/hf_cache/out/refinedweb_01_0/fasttext/fasttext_filter/1b-data_influence_model-prediction/cluster_info"
path_str_type: "S24"
ncentroids: 10000
dataset_size: 29478616
emb_size: 768
niter: 100
seed: 1234
selection_ratio: 0.5